server:
  port: 9980
spring:
  application:
    name: vicente-crawler
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  #数据库配置
  datasource:
    name: itender
    url: jdbc:mysql://192.168.235.3:3306/xxl-job?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: bigdata
    password: 'bluemoon2018#'
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: "SELECT 'x'"
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 10
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: true
    keepAlive: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    encoding: UTF-8
    basename: message/messages_zh
snowflake:
  inst:
    workerId: 1
    datacenterId : 1


