server:
  port: 9980
spring:
  application:
    name: vicente-crawler
  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.243.20:9097/user_role?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 'b#12345678'
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: "SELECT 'x'"
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 10
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: true
    keepAlive: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    encoding: UTF-8
    basename: message/messages_zh


# Logger Config
logging:
  level:
    cn.com.bluemoon.demo: debug

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'


